import { Story } from './types';

export const MOCK_STORIES: Story[] = [
  {
    id: '1',
    title: 'Hành Trình Về Phương Đông',
    description: 'Một cái nhìn sâu sắc về tâm linh và văn hóa phương Đông qua con mắt của các nhà khoa học phương Tây. Bản edit trau chuốt bởi tớ.',
    warning: 'Nội dung có tính triết học sâu sắc, cần sự tập trung cao độ.',
    info: 'Tác phẩm được chuyển thể từ tư liệu gốc của đoàn thám hiểm Anh.',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400',
    authorId: 'a1',
    authorName: 'Nguyên Phong',
    originalAuthor: 'Sutherland Macdonald',
    categories: ['Tâm linh', 'Khoa học', 'Hồi ký'],
    status: 'completed',
    views: 12500,
    rating: 4.8,
    chapterCount: 15,
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: '2',
    title: 'Kiêu Hãnh Và Định Kiến',
    description: 'Câu chuyện tình yêu đầy trắc trở giữa Elizabeth Bennet và Quý ngài Darcy. Tác phẩm kinh điển tớ vừa mới edit xong với ngôn từ hiện đại hơn.',
    warning: 'Truyện chứa các tình tiết xã hội cổ điển, không dành cho người thích tốc độ nhanh.',
    info: 'Tác phẩm kinh điển được giảng dạy tại nhiều trường đại học.',
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400',
    authorId: 'a1',
    authorName: 'Nguyên Phong',
    originalAuthor: 'Jane Austen',
    categories: ['Lãng mạn', 'Cổ điển'],
    status: 'ongoing',
    views: 8400,
    rating: 4.9,
    chapterCount: 45,
    createdAt: Date.now() - 86400000 * 60,
    updatedAt: Date.now() - 3600000,
  },
  {
    id: '3',
    title: 'Người Đua Diều',
    description: 'Một câu chuyện cảm động về tình bạn, tội lỗi và sự chuộc lỗi. Đây là bản edit mới nhất của tớ dành cho kiệt tác này.',
    warning: 'Có những cảnh bạo lực và tâm lý nặng nề.',
    info: 'Tác phẩm đạt giải thưởng văn học quốc tế.',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400',
    authorId: 'a1',
    authorName: 'Nguyên Phong',
    originalAuthor: 'Khaled Hosseini',
    categories: ['Văn học', 'Chiến tranh'],
    status: 'completed',
    views: 25000,
    rating: 4.7,
    chapterCount: 22,
    createdAt: Date.now() - 86400000 * 100,
    updatedAt: Date.now() - 86400000 * 10,
  }
];
